# Generated by Django 5.2.4 on 2025-12-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bugreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot/'),
        ),
    ]
